require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BarriersController do

  # This should return the minimal set of attributes required to create a valid
  # Barrier. As you add validations to Barrier, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all barriers as @barriers" do
      barrier = Barrier.create! valid_attributes
      get :index
      assigns(:barriers).should eq([barrier])
    end
  end

  describe "GET show" do
    it "assigns the requested barrier as @barrier" do
      barrier = Barrier.create! valid_attributes
      get :show, :id => barrier.id.to_s
      assigns(:barrier).should eq(barrier)
    end
  end

  describe "GET new" do
    it "assigns a new barrier as @barrier" do
      get :new
      assigns(:barrier).should be_a_new(Barrier)
    end
  end

  describe "GET edit" do
    it "assigns the requested barrier as @barrier" do
      barrier = Barrier.create! valid_attributes
      get :edit, :id => barrier.id.to_s
      assigns(:barrier).should eq(barrier)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Barrier" do
        expect {
          post :create, :barrier => valid_attributes
        }.to change(Barrier, :count).by(1)
      end

      it "assigns a newly created barrier as @barrier" do
        post :create, :barrier => valid_attributes
        assigns(:barrier).should be_a(Barrier)
        assigns(:barrier).should be_persisted
      end

      it "redirects to the created barrier" do
        post :create, :barrier => valid_attributes
        response.should redirect_to(Barrier.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved barrier as @barrier" do
        # Trigger the behavior that occurs when invalid params are submitted
        Barrier.any_instance.stub(:save).and_return(false)
        post :create, :barrier => {}
        assigns(:barrier).should be_a_new(Barrier)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Barrier.any_instance.stub(:save).and_return(false)
        post :create, :barrier => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested barrier" do
        barrier = Barrier.create! valid_attributes
        # Assuming there are no other barriers in the database, this
        # specifies that the Barrier created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Barrier.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => barrier.id, :barrier => {'these' => 'params'}
      end

      it "assigns the requested barrier as @barrier" do
        barrier = Barrier.create! valid_attributes
        put :update, :id => barrier.id, :barrier => valid_attributes
        assigns(:barrier).should eq(barrier)
      end

      it "redirects to the barrier" do
        barrier = Barrier.create! valid_attributes
        put :update, :id => barrier.id, :barrier => valid_attributes
        response.should redirect_to(barrier)
      end
    end

    describe "with invalid params" do
      it "assigns the barrier as @barrier" do
        barrier = Barrier.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Barrier.any_instance.stub(:save).and_return(false)
        put :update, :id => barrier.id.to_s, :barrier => {}
        assigns(:barrier).should eq(barrier)
      end

      it "re-renders the 'edit' template" do
        barrier = Barrier.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Barrier.any_instance.stub(:save).and_return(false)
        put :update, :id => barrier.id.to_s, :barrier => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested barrier" do
      barrier = Barrier.create! valid_attributes
      expect {
        delete :destroy, :id => barrier.id.to_s
      }.to change(Barrier, :count).by(-1)
    end

    it "redirects to the barriers list" do
      barrier = Barrier.create! valid_attributes
      delete :destroy, :id => barrier.id.to_s
      response.should redirect_to(barriers_url)
    end
  end

end
